!
! Zebra configuration saved from vty
!   2025/11/25 14:15:32
!
hostname Zebra
password root
enable password root
log stdout
log syslog
log record-priority
log timestamp precision 3
!
configure radio
 
!
line vty
 exec-timeout 0 0
!
